services:
  # mongodb:
  #   image: mongodb/mongodb-community-server:7.0-ubi8
  #   volumes:
  #     - type: bind
  #       source: ./data/mongodb
  #       target: /data/db
  #   ports:
  #     - 27017:27017
  #   restart: unless-stopped
  #   user: 1000:1000
  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data/valkey:/data
  sea_orm:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: agin-class-manager
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql
