/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check server health
         * @description This endpoint returns `ok`
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log in */
        get: operations["log_in"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log out
         * @description Clears the user session, removes the OIDC 'id' cookie, and redirects to the OIDC end-session endpoint.
         */
        get: operations["log_out"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all organizations */
        get: operations["get_organizations"];
        put?: never;
        /** Create a new organization */
        post: operations["create_organization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{org_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get organization by id */
        get: operations["get_organization_by_id"];
        put?: never;
        post?: never;
        /** Delete organization by id */
        delete: operations["delete_organization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{org_id}/fundraising": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all fundraisings for an organization */
        get: operations["get_fundraisings"];
        put?: never;
        /** Create a new fundraising */
        post: operations["create_fundraising"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add member to organization */
        post: operations["add_member_to_organization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/organizations/{org_id}/santa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a secret santa for an organization */
        get: operations["get_secret_santa"];
        put?: never;
        /** Initialize secret santa */
        post: operations["create_secret_santa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user details */
        get: operations["get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @example {
         *       "id": "60c72b2f9b1d8c001c8e4f5a",
         *       "success": true
         *     } */
        CreateSuccess: {
            /** Format: int64 */
            id: number;
            success: boolean;
        };
        FundraisingRes: {
            description: string;
            /** Format: date-time */
            end_date?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            /** Format: int64 */
            organization_id: number;
            payers: components["schemas"]["PayerRes"][];
            /** Format: date-time */
            start_date?: string | null;
            /** Format: int64 */
            total_amount: number;
        };
        GenericError: {
            error: string;
        };
        GetUserRes: {
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
            organizations: components["schemas"]["StrippedOrg"][];
            subject: string;
        };
        Membership: {
            role: components["schemas"]["OrganizationRole"];
            /** Format: int64 */
            user_id: number;
        };
        Model: {
            avatar_url?: string | null;
            /** Format: int64 */
            budget: number;
            description: string;
            /** Format: int64 */
            id: number;
            name: string;
            slug: string;
        };
        /** @description MutableFundraising is used for creating or updating fundraising throught the API. */
        MutableFundraising: {
            description: string;
            /** Format: date-time */
            end_date?: string | null;
            name: string;
            payers: components["schemas"]["Payer"][];
            /** Format: date-time */
            start_date?: string | null;
            /** Format: int64 */
            total_amount: number;
        };
        /** @description MutableOrganization is used for creating or updating organization throught the API. */
        MutableOrganization: {
            avatar_url?: string | null;
            description: string;
            name: string;
            slug?: string | null;
        };
        MutableSanta: {
            /** Format: date-time */
            end_date?: string | null;
            participants: number[];
            /** Format: date-time */
            propositions_due?: string | null;
            /** Format: date-time */
            start_date?: string | null;
        };
        /** @example {
         *       "error": "Not Found"
         *     } */
        NotFoundError: {
            error: string;
        };
        OrgUser: {
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
            role: components["schemas"]["OrganizationRole"];
        };
        OrganizationRes: {
            avatar_url?: string | null;
            /** Format: int64 */
            budget: number;
            description: string;
            /** Format: int64 */
            id: number;
            members: components["schemas"]["Membership"][];
            name: string;
            slug: string;
        };
        OrganizationResponse: components["schemas"]["Model"] | components["schemas"]["PopulatedOrganization"];
        /** @enum {string} */
        OrganizationRole: "member" | "admin";
        PatchMemberPayload: {
            email: string;
            role: components["schemas"]["OrganizationRole"];
        };
        Payer: {
            /**
             * Format: int64
             * @description Custom amout that this user has to pay, if empty, then it's automatically divided evenly between users
             */
            amount_to_pay?: number | null;
            comment: string;
            /**
             * Format: int64
             * @description If empty, defaults to zero
             */
            paid_amount?: number | null;
            /** Format: int64 */
            user_id: number;
        };
        PayerRes: {
            /** Format: int64 */
            amount_to_pay: number;
            comment: string;
            /** Format: int64 */
            paid_amount: number;
            /** Format: int64 */
            user_id: number;
        };
        PopulatedOrganization: {
            avatar_url?: string | null;
            /** Format: int64 */
            budget: number;
            description: string;
            /** Format: int64 */
            id: number;
            members: components["schemas"]["OrgUser"][];
            name: string;
            slug: string;
        };
        PopulatedSanta: {
            /** Format: date-time */
            end_date: string;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            organization_id: number;
            participants: components["schemas"]["SantaParticipant"][];
            /** Format: date-time */
            propositions_due?: string | null;
            /** Format: date-time */
            start_date: string;
        };
        SantaParticipant: {
            email: string;
            /** Format: int64 */
            id: number;
            name: string;
            proposition?: string | null;
            /** Format: int64 */
            receiver?: number | null;
        };
        StrippedOrg: {
            avatar_url?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
        };
        /** @example {
         *       "success": true
         *     } */
        Success: {
            success: boolean;
        };
        /** @example {
         *       "error": "Unauthorized"
         *     } */
        UnauthorizedError: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    log_in: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    log_out: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: never;
    };
    get_organizations: {
        parameters: {
            query?: {
                /** @description Include detailed user information for members */
                "user-details"?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    create_organization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutableOrganization"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRes"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_organization_by_id: {
        parameters: {
            query?: {
                /** @description Include detailed user information for members */
                "user-details"?: boolean;
            };
            header?: never;
            path: {
                /** @description Organization id */
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    delete_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id */
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_fundraisings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id */
                org_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FundraisingRes"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    create_fundraising: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id */
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutableFundraising"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    add_member_to_organization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id */
                org_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMemberPayload"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericError"];
                };
            };
            /** @description Organization not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
        };
    };
    get_secret_santa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PopulatedSanta"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    create_secret_santa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MutableSanta"];
            };
        };
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateSuccess"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
    get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetUserRes"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthorizedError"];
                };
            };
        };
    };
}
